name: Build and publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_and_publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.45

      - name: Install packages
        run: bun install

      - name: Build
        run: bun run build

      - name: Test
        run: bun test

      - name: Publish
        run: npm publish --provenance --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
